### ISSUE TITLE
plugin gives FEAGI port instead of 9055 to games on local/playground

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/godot_feagi_integration#10]
https://github.com/feagi/godot_feagi_integration/blob/main/addons/FeagiIntegration/Configuration/FEAGI_Resource_Endpoint.gd#L52

it goes to ws://127.0.0.1:8000 when it should be ws://127.0.0.1:9055

**Comment by Amir-Rasteg** [comment]
Please test the latest branch at https://github.com/feagi/godot_feagi_integration/tree/advanced-docs2 (bit of a mess right now)

**Comment by Amir-Rasteg** [comment]
fixed an issue regarding incorrect mapping, give it a test

**Comment by Kakcalu13** [comment]
confirmed
