### ISSUE TITLE
motion control spams logs

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/godot_feagi_integration#11]
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/50ae10b2-862f-43d3-bfa8-8b480e111728">

**Comment by Kakcalu13** [comment]
![image](https://github.com/user-attachments/assets/2a9cad86-897b-476d-a544-21437e2f9055)

**Comment by Amir-Rasteg** [comment]
THis has been addressed ina  push, but due to the random nature of this issue, lets hold open this issue a while longer

**Comment by Amir-Rasteg** [comment]
This specific issue has been resolved, however another type of error can occur randomly, a separate github issue will be made for it
