### ISSUE TITLE
Networking issue when it comes to cloud or playground

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/godot_feagi_integration#6]
When it's on local, see here:

![image](https://github.com/user-attachments/assets/b3ddc07b-b581-473c-b24c-ae16e91bf8c0)

it worked well.

When it comes to playground:
![image](https://github.com/user-attachments/assets/ecfea9f1-5d09-439f-a851-90020d1458a4)

The "http" is missing. The addon is not included

**Comment by Kakcalu13** [comment]
I suspect it's due to no addons folder which is why it caused failure

**Comment by Kakcalu13** [comment]
To test if it's working properly, use playground. pull latest on playground and test it.

**Comment by Amir-Rasteg** [comment]
this has been fixed
